# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: package-lock.json|yarn.lock
repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
        args: ["--custom-plugins=detect-secrets-plugin/custom-secrete-plugin.py"]
